use crate::model::{PackageKind, PackageModel};
use crate::util::normalize_arch;

pub fn sanitize_pkgver(version: &str) -> (Option<u32>, String) {
    let (epoch, rest) = match version.split_once(':') {
        Some((e, r)) if e.chars().all(|c| c.is_ascii_digit()) && !e.is_empty() => {
            (e.parse().ok(), r)
        }
        _ => (None, version),
    };
    let mut v: String = rest
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '.' || c == '_' || c == '+' {
                c
            } else {
                '_'
            }
        })
        .collect();
    while v.starts_with(|c: char| !c.is_ascii_alphanumeric()) {
        v.remove(0);
    }
    if v.is_empty() {
        v = "0".into();
    }
    (epoch, v)
}

pub fn arch_array(arch: &str) -> &'static str {
    match normalize_arch(arch).as_str() {
        "any" => "'any'",
        "aarch64" => "'aarch64'",
        "arm" => "'armv7h'",
        "x86" => "'i686'",
        _ => "'x86_64'",
    }
}

fn bash_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}

fn shell_string(s: &str) -> String {
    format!(
        "\"{}\"",
        s.replace('\\', "\\\\")
            .replace('"', "\\\"")
            .replace('$', "\\$")
            .replace('`', "\\`")
    )
}

pub fn generate(
    model: &PackageModel,
    pkgname: &str,
    depends: &[String],
    source_name: &str,
) -> String {
    let (epoch, pkgver) = sanitize_pkgver(&model.version);
    let mut out = String::new();
    out.push_str(&format!(
        "# Generated by ZLynstall from {}\n",
        model
            .source_path
            .file_name()
            .map(|s| s.to_string_lossy().into_owned())
            .unwrap_or_default()
    ));
    out.push_str("# Maintainer scripts of the original package are intentionally not run.\n\n");
    out.push_str(&format!("pkgname={pkgname}\n"));
    out.push_str(&format!("pkgver={pkgver}\n"));
    out.push_str("pkgrel=1\n");
    if let Some(e) = epoch {
        out.push_str(&format!("epoch={e}\n"));
    }
    out.push_str(&format!(
        "pkgdesc={}\n",
        shell_string(model.summary.as_deref().unwrap_or(&model.display_name))
    ));
    out.push_str(&format!("arch=({})\n", arch_array(&model.arch)));
    if let Some(url) = &model.homepage {
        out.push_str(&format!("url={}\n", shell_string(url)));
    }
    let license = model
        .license
        .as_deref()
        .filter(|l| !l.trim().is_empty())
        .unwrap_or("custom");
    out.push_str(&format!("license=({})\n", bash_quote(license)));
    if !depends.is_empty() {
        out.push_str(&format!(
            "depends=({})\n",
            depends
                .iter()
                .map(|d| bash_quote(d))
                .collect::<Vec<_>>()
                .join(" ")
        ));
    }
    out.push_str("options=('!strip' '!debug' 'emptydirs')\n");
    out.push_str(&format!("source=({})\n", bash_quote(source_name)));
    out.push_str(&format!("noextract=({})\n", bash_quote(source_name)));
    out.push_str("sha256sums=('SKIP')\n\n");
    out.push_str("package() {\n");
    match model.kind {
        PackageKind::Deb => {
            out.push_str(&format!("  bsdtar -xOf \"$srcdir/{source_name}\" 'data.tar*' | bsdtar -xpf - -C \"$pkgdir\"\n"));
        }
        PackageKind::Rpm => {
            out.push_str(&format!(
                "  bsdtar -xpf \"$srcdir/{source_name}\" -C \"$pkgdir\"\n"
            ));

            out.push_str("  rm -rf \"$pkgdir/usr/lib/.build-id\" \"$pkgdir/usr/lib/debug\"\n");
        }
        PackageKind::AppImage => {}
    }
    out.push_str("  chmod 755 \"$pkgdir\"\n");
    out.push_str("}\n");
    out
}

#[cfg(test)]
pub(crate) mod tests {
    use super::*;
    use crate::model::PackageKind;
    use std::path::PathBuf;

    pub(crate) fn sample_model() -> PackageModel {
        PackageModel {
            kind: PackageKind::Deb,
            source_path: PathBuf::from("/home/u/Downloads/discord-0.0.99.deb"),
            file_size: 1,
            name: "discord".into(),
            display_name: "Discord".into(),
            version: "1:0.0.99-2ubuntu1".into(),
            arch: "amd64".into(),
            summary: Some("All-in-one voice and text chat \"for gamers\"".into()),
            description: None,
            homepage: Some("https://discord.com".into()),
            license: None,
            maintainer: None,
            installed_size: None,
            dependencies: vec![],
            desktop_entries: vec![],
            icon_data_url: None,
            file_count: 0,
            top_level_paths: vec![],
        }
    }

    #[test]
    fn pkgver_sanitising() {
        assert_eq!(
            sanitize_pkgver("1:0.0.99-2ubuntu1"),
            (Some(1), "0.0.99_2ubuntu1".into())
        );
        assert_eq!(sanitize_pkgver("2.10-9.fc38"), (None, "2.10_9.fc38".into()));
        assert_eq!(sanitize_pkgver("-weird"), (None, "weird".into()));
        assert_eq!(sanitize_pkgver(""), (None, "0".into()));
    }

    #[test]
    fn pkgbuild_snapshot() {
        let text = generate(
            &sample_model(),
            "discord",
            &["gtk3".into(), "libnotify".into()],
            "source.deb",
        );
        insta::assert_snapshot!(text);
    }
}
