use std::collections::HashSet;

use crate::model::PackageModel;
use crate::util::normalize_arch;

pub fn sanitize_version(version: &str) -> String {
    let no_epoch = version.split_once(':').map(|(_, r)| r).unwrap_or(version);
    let mut v: String = no_epoch
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '.' || c == '_' || c == '+' || c == '~' || c == '^'
            {
                c
            } else {
                '.'
            }
        })
        .collect();
    while v.starts_with('.') {
        v.remove(0);
    }
    if v.is_empty() {
        v = "0".into();
    }
    v
}

pub fn rpm_arch(arch: &str) -> Option<&'static str> {
    match normalize_arch(arch).as_str() {
        "any" => Some("noarch"),
        _ => None,
    }
}

fn is_standard_dir(path: &str) -> bool {
    const STD: &[&str] = &[
        "/usr",
        "/usr/bin",
        "/usr/sbin",
        "/usr/lib",
        "/usr/lib64",
        "/usr/libexec",
        "/usr/share",
        "/usr/share/applications",
        "/usr/share/doc",
        "/usr/share/man",
        "/usr/share/icons",
        "/usr/share/icons/hicolor",
        "/usr/share/pixmaps",
        "/usr/share/metainfo",
        "/usr/share/appdata",
        "/usr/share/mime",
        "/usr/share/mime/packages",
        "/usr/share/licenses",
        "/usr/share/locale",
        "/usr/share/bash-completion",
        "/usr/share/bash-completion/completions",
        "/usr/share/zsh",
        "/usr/share/zsh/site-functions",
        "/usr/share/fish",
        "/usr/share/fish/vendor_completions.d",
        "/usr/share/polkit-1",
        "/usr/share/polkit-1/actions",
        "/usr/share/dbus-1",
        "/usr/share/dbus-1/services",
        "/usr/share/glib-2.0",
        "/usr/share/glib-2.0/schemas",
        "/usr/share/lintian",
        "/usr/share/lintian/overrides",
        "/usr/share/menu",
        "/usr/local",
        "/usr/local/bin",
        "/usr/local/share",
        "/usr/local/lib",
        "/etc",
        "/etc/xdg",
        "/etc/apt",
        "/etc/apt/sources.list.d",
        "/etc/cron.daily",
        "/opt",
        "/var",
        "/var/lib",
        "/lib",
        "/lib64",
        "/bin",
        "/sbin",
    ];
    if STD.contains(&path) {
        return true;
    }

    let mut parts = path.trim_start_matches('/').split('/');
    match (
        parts.next(),
        parts.next(),
        parts.next(),
        parts.next(),
        parts.next(),
        parts.next(),
    ) {
        (Some("usr"), Some("share"), Some("man"), Some(_), None, _) => true,
        (Some("usr"), Some("share"), Some("icons"), Some("hicolor"), Some(_), rest) => {
            rest.is_none() || rest == Some("apps") || rest == Some("mimetypes")
        }
        (Some("usr"), Some("share"), Some("locale"), Some(_), rest, _) => {
            rest.is_none() || rest == Some("LC_MESSAGES")
        }
        (Some("usr"), Some("share"), Some("doc"), Some(_), None, _) => false,
        _ => false,
    }
}

pub fn files_list(tree: &[(String, bool, bool)]) -> String {
    let mut out = String::from("%defattr(-,root,root,-)\n");
    let mut seen: HashSet<&str> = HashSet::new();
    for (path, is_dir, _is_link) in tree {
        if !seen.insert(path) {
            continue;
        }
        if *is_dir {
            if !is_standard_dir(path) {
                out.push_str(&format!("%dir \"{}\"\n", path.replace('"', "\\\"")));
            }
        } else if path.starts_with("/usr/share/doc/") {
            out.push_str(&format!("%doc \"{}\"\n", path.replace('"', "\\\"")));
        } else {
            out.push_str(&format!("\"{}\"\n", path.replace('"', "\\\"")));
        }
    }
    out
}

fn spec_escape(s: &str) -> String {
    s.replace('%', "%%")
        .lines()
        .next()
        .unwrap_or("")
        .trim()
        .to_string()
}

pub fn spec(
    model: &PackageModel,
    name: &str,
    requires: &[String],
    tree_dir: &str,
    files_list_path: &str,
) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "# Generated by ZLynstall from {}\n",
        model
            .source_path
            .file_name()
            .map(|s| s.to_string_lossy().into_owned())
            .unwrap_or_default()
    ));
    out.push_str("# Maintainer scripts of the original package are intentionally not run.\n\n");
    out.push_str("%global __os_install_post %{nil}\n");
    out.push_str("%global __strip /bin/true\n");
    out.push_str("%global _build_id_links none\n");
    out.push_str("%global debug_package %{nil}\n");
    out.push_str("%global _missing_build_ids_terminate_build 0\n");
    out.push_str("%global __requires_exclude .*\n");
    out.push_str("%global __provides_exclude .*\n");
    out.push_str("%undefine _debugsource_packages\n");
    out.push_str("%undefine _debuginfo_subpackages\n\n");
    out.push_str(&format!("Name: {name}\n"));
    out.push_str(&format!("Version: {}\n", sanitize_version(&model.version)));
    out.push_str("Release: 1\n");
    out.push_str(&format!(
        "Summary: {}\n",
        spec_escape(model.summary.as_deref().unwrap_or(&model.display_name))
    ));
    out.push_str(&format!(
        "License: {}\n",
        spec_escape(
            model
                .license
                .as_deref()
                .filter(|l| !l.trim().is_empty())
                .unwrap_or("Proprietary")
        )
    ));
    if let Some(url) = &model.homepage {
        out.push_str(&format!("URL: {}\n", spec_escape(url)));
    }
    if let Some(a) = rpm_arch(&model.arch) {
        out.push_str(&format!("BuildArch: {a}\n"));
    }
    out.push_str("AutoReqProv: no\n");
    for r in requires {
        out.push_str(&format!("Requires: {r}\n"));
    }
    out.push_str("\n%description\n");
    let desc = model
        .description
        .clone()
        .or_else(|| model.summary.clone())
        .unwrap_or_else(|| model.display_name.clone());
    for line in desc.lines().take(40) {
        out.push_str(&format!("{}\n", line.replace('%', "%%")));
    }
    out.push_str("\n%prep\n# nothing to do\n\n%build\n# nothing to do\n\n");
    out.push_str("%install\n");
    out.push_str("rm -rf \"%{buildroot}\"\nmkdir -p \"%{buildroot}\"\n");
    out.push_str(&format!("cp -a \"{tree_dir}/.\" \"%{{buildroot}}/\"\n\n"));
    out.push_str(&format!("%files -f {files_list_path}\n"));
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn versions() {
        assert_eq!(sanitize_version("1:0.0.99-2ubuntu1"), "0.0.99.2ubuntu1");
        assert_eq!(sanitize_version("2.10"), "2.10");
    }

    #[test]
    fn owns_only_non_standard_dirs() {
        let tree = vec![
            ("/usr".into(), true, false),
            ("/usr/bin".into(), true, false),
            ("/usr/bin/discord".into(), false, false),
            ("/usr/share/icons/hicolor/256x256/apps".into(), true, false),
            (
                "/usr/share/icons/hicolor/256x256/apps/discord.png".into(),
                false,
                false,
            ),
            ("/opt".into(), true, false),
            ("/opt/Discord".into(), true, false),
            ("/opt/Discord/Discord".into(), false, false),
            ("/usr/share/doc/discord".into(), true, false),
            ("/usr/share/doc/discord/copyright".into(), false, false),
        ];
        insta::assert_snapshot!(files_list(&tree));
    }

    #[test]
    fn spec_snapshot() {
        let model = crate::convert::pkgbuild::tests::sample_model();
        insta::assert_snapshot!(spec(
            &model,
            "discord",
            &[
                "libgtk-3.so.0()(64bit)".into(),
                "libnotify.so.4()(64bit)".into()
            ],
            "/tmp/build/root",
            "/tmp/build/files.list"
        ));
    }
}
